apiVersion: kubescheduler.operator.openshift.io/v1alpha1
kind: KubeSchedulerOperatorConfig
metadata:
  name: instance
spec:
  managementState: Managed
  imagePullSpec: openshift/origin-hyperkube:latest
  version: 3.11.0
  logging:
    level: 4
  replicas: 2