apiVersion: operator.openshift.io/v1
kind: KubeScheduler
metadata:
  name: cluster
  annotations:
    release.openshift.io/create-only: "true"
spec:
  managementState: Managed
  logging:
    level: 4
